---
namespace: betagouv
name: common_base_roles
version: 1.6.0
readme: README.md
authors:
  - Aurélien Merel <aurelien.merel@beta.gouv.fr>
description: Some common base roles for beta.gouv.fr
license: WTFPL
repository: https://github.com/betagouv/ansible-pole-api
issues: https://github.com/betagouv/ansible-pole-api/issues
