---
argument_specs:
  main:
    author:
      - Aurélien Merel
    version_added: 1.4.0
    options:
      encrypted_volumes_base_dir:
        type: str
        description: 'Chaque partition chiffrée sera montée dans un sous-répertoire de ce dossier de base'
      encrypted_volumes:
        type: list
        elements: dict
        description: 'Chaque élement de la liste décrit une partition chiffrée. Clés : C(device) est le périphérique dans C(/dev), C(name) un nom de votre choix pour cette partition et C(passphrase) la phrase de passe de (dé)chiffrement.'
      encrypted_services_data:
        type: list
        elements: dict
        description:
          - Définit des unités systemd dont le démarrage est bloqué tant que des répertoires chiffrés ne sont pas montés. Concrètement, les répertoires en question sont attachés avec C(mount --bind) à un répertoire dans un volume chiffré.
          - Chaque élément de la liste contient une clé C(storage) et une clé C(units).
          - C(units) est une liste de chaines de caractères, et chaque élément est un nom d'unité systemd dont le démarrage est bloqué tant que les répertoires ne sont pas montés.
          - "C(storage) liste les répertoires protégés devant être monter pour démarrer les unités listées dans C(units). Chaque élément de la liste est un dictionnaire. La clé C(volume) est égale à l'un des volumes définis avec C(name) dans la variable C(encrypted_volumes). La clé C(binds) est une liste de dictionnaires à deux clés : C(target) le répertoire sur le système à protéger (p. ex. C(/var/lib/redis)) et C(subdir) le sous-dossier du volume chiffré auquel le dossier sur le système sera attaché avec C(mount --bind) (p. ex. C(redis/data))."
